name: password
description: "A new Flutter project."
publish_to: 'none'
version: 0.4.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  image_path: "assets/icon2.png"
  adaptive_icon_background: "#000000"

flutter_native_splash:
  color: "#000000"
  image: assets/icon2.png
  android: true
  android_gravity: center

flutter:
  uses-material-design: true
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
        

