// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd606bHBmzovZc8xUgTAQ3PPo-F0ob9WU',
    appId: '1:104288185304:web:ece1c04df77be0733da0ad',
    messagingSenderId: '104288185304',
    projectId: 'password-8792d',
    authDomain: 'password-8792d.firebaseapp.com',
    storageBucket: 'password-8792d.firebasestorage.app',
    measurementId: 'G-1S9Z8J63PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrSUplBkwBIyPfeLhK7lrySd8GJyXKdzQ',
    appId: '1:104288185304:android:a25aef85a12f60603da0ad',
    messagingSenderId: '104288185304',
    projectId: 'password-8792d',
    storageBucket: 'password-8792d.firebasestorage.app',
  );
}
